openapi: 3.0.0
info:
  title: sample_api
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{user_id}':
    parameters:
      - schema:
          type: string
        name: user_id
        in: path
        required: true
    get:
      summary: ユーザー取得
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      name:
                        type: string
              example:
                name: Jessica Smith
      operationId: get-user_id
      description: ''
      tags:
        - user
components:
  schemas: {}
